SET @userName = (SELECT SUBSTR(USER(), 1, LOCATE('@', USER())-1));
SET SESSION group_concat_max_len = 65535;

SET @cmd2 = (SELECT GROUP_CONCAT(CONCAT('DROP DATABASE `', SCHEMA_NAME, '`;') SEPARATOR '\r\n') AS `DROP_QUERY`
FROM information_schema.schemata
WHERE schema_name NOT IN('sys','mysql','information_schema','performance_schema','phpmyadmin'));

-- SQL Script for commit
SELECT CONCAT(
	'-- Query has been generated by ', @userName, '\n\n',
	'TRANSACTION START;\n',
	@cmd2, '\n\n\-- COMMIT;'
) AS `drop_databases.sql`;
