SET SESSION group_concat_max_len = 65535;
SET @suffix = '$$\n\nDELIMITER ;\n';
SET @prefix = CONCAT('CREATE\n/*!50017 DEFINER = `root`@`localhost` */\nTRIGGER ',DATABASE(),'.');

SELECT CONCAT('DELIMITER $$\nDROP TRIGGER IF EXISTS ',DATABASE(), '.', `TRIGGER_NAME`, '$$\n\n', @prefix, `TRIGGER_NAME`, ' ', `ACTION_TIMING`, ' ', `EVENT_MANIPULATION`, ' ON `', `EVENT_OBJECT_TABLE`, '`\nFOR EACH ROW ', `ACTION_STATEMENT`, @suffix) AS SQL_QUERIES 
FROM INFORMATION_SCHEMA.TRIGGERS WHERE TRIGGER_SCHEMA=DATABASE();

SELECT * FROM INFORMATION_SCHEMA.TRIGGERS WHERE TRIGGER_SCHEMA=DATABASE();
